require "faker"

Trivium.destroy_all
Question.destroy_all
Answer.destroy_all
User.destroy_all
Game.destroy_all

tr1 = Trivium.create({ title:"Facts of Harry Potter", content:"In this trivia you could find questions about all movies of Harry Potter,will prepared this is not going to be an easy path my young wizzard"})
tr2 = Trivium.create({ title:"Harry Potter spells ", content:"You want to test your knowledge about spells? Check this out" })
tr3 = Trivium.create({ title:"Harry Potter Randoms ", content:"Do you know everything about Harry Potter? Prove it in this quizz"})

us1 = User.create({name:"Harry",email_address: "magic@gmail.com",user_name:"Harryp1", password:"magic"})

ga1 = Game.create({user_id:us1.id, trivium_id:tr1.id, result: 50})
ga1 = Game.create({user_id:us1.id, trivium_id:tr2.id, result: 50})

 tq1 = Question.create({content:"What house at Hogwarts does Harry belong to?", image:"https://nexter.org/wp-content/uploads/2018/09/harry-potter-sorting-hat-hogwarts-quiz.jpg",trivium_id:tr1.id})
 tq2 = Question.create({content:"What position does Harry play on his Quidditch team?", image:"https://cdn.unifiedcommerce.com/content/product/large/819844012267.jpg",trivium_id:tr1.id})
 tq3 = Question.create({content:"What power do the dementors have over people?",trivium_id:tr1.id})
 tq4 = Question.create({content:"Is one of the three illegal curses and allows the wizard to control the actions of another person.", image:"https://s3.amazonaws.com/charitycdn/cache/resizedcrop-fd3045706b4e0682a31ccfb68fb5e58d-800x800.jpg",trivium_id:tr1.id})
 tq5 = Question.create({content:"Is a person that is trained to catch Dark wizards.", image:"https://lh3.googleusercontent.com/proxy/O2wFYO2gKyoAmMmdOmaRI51NAx5qZCYMO_M3WRu2ci2iTkNhptTarMFR90xS4h1_pz9P2A7E2zGyZMXYKoqp2X7rR8t4K6LYzqEnCnEBfTjsM68Sl5MlenhORHhHzePTSt0VT2_TWdJc_mU1XJEQfV2Y",trivium_id:tr1.id})
 tq6  = Question.create({content:" Who is Nagini?",trivium_id:tr3.id})
 tq7 = Question.create({content:"How does Harry catch his first snitch?",trivium_id:tr3.id})
tq8 = Question.create({content:"What magical talent does Harry share with Voldemort?", image:"https://s.driving-tests.org/wp-content/uploads/autotest/1293175946_IndianaQ4.svg",trivium_id:tr3.id})
tq9 = Question.create({content:" Who kills Professor Dumbledore?", image:"https://img.women.com/images/images/000/174/635/large/triwizard_cup_jpeg.jpg?1551654502",trivium_id:tr3.id})
tq10 = Question.create({content:"Which character became a professional Quidditch player?",trivium_id:tr3.id})

tq11 = Question.create({content:"This practical spell will shine a light on nearly any situation.",trivium_id:tr1.id})
tq12 = Question.create({content:"Which spell could be used in place of a microphone?",trivium_id:tr2.id})
tq13 = Question.create({content:"Which bewitching charm did Hermione master long before her peers?",trivium_id:tr2.id})
tq14 = Question.create({content:"Harry Potter used the Accio spell to defeat what creature?",trivium_id:tr2.id})
tq15 = Question.create({content:"Which spell would be useful when planning a bonfire?",trivium_id:tr2.id})


ta1 = Answer.create({content:"Slytherin",solution:false, question_id:tq1.id})
ta2 = Answer.create({content:"Hufflepuff",solution:false, question_id:tq1.id})
ta3 = Answer.create({content:"Ravenclaw",solution:false, question_id:tq1.id})
ta4 = Answer.create({content:"Gryffindor",solution:true, question_id:tq1.id})
ta5= Answer.create({content:"Receiver",solution:false, question_id:tq2.id})
ta6= Answer.create({content:"Keeper",solution:false, question_id:tq2.id})
ta7= Answer.create({content:"Bludger",solution:false, question_id:tq2.id})
ta8= Answer.create({content:"Seeker",solution:true, question_id:tq2.id})
ta9= Answer.create({content:"They make them go crazy",solution:false, question_id:tq3.id})
ta10= Answer.create({content:"They convince them to be evil",solution:false, question_id:tq3.id})
ta11= Answer.create({content:"They drain them from all happiness",solution:true, question_id:tq3.id})
ta12= Answer.create({content:"They make them do their bidding",solution:false, question_id:tq3.id})
ta13= Answer.create({content:Faker::Movies::HarryPotter.spell,solution:false, question_id:tq4.id})
ta14= Answer.create({content:Faker::Movies::HarryPotter.spell,solution:false, question_id:tq4.id})
ta15= Answer.create({content:Faker::Movies::HarryPotter.spell,solution:false, question_id:tq4.id})
ta16= Answer.create({content:"Imperius",solution:true, question_id:tq4.id})
ta17= Answer.create({content:"Auror",solution:true, question_id:tq5.id})
ta18= Answer.create({content:"A wizard of trust",solution:false, question_id:tq5.id})
ta19= Answer.create({content:"Policeman of magic",solution:false, question_id:tq5.id})
ta20= Answer.create({content:"Voldemort knights",solution:false, question_id:tq5.id})
ta21= Answer.create({content:"A powerful wizard",solution:false, question_id:tq6.id})
ta22= Answer.create({content:"Voldemor's old love'",solution:false, question_id:tq6.id})
ta23= Answer.create({content:"Tom Riddles's horcrux",solution:true, question_id:tq6.id})
ta24= Answer.create({content:"A big dragon",solution:false, question_id:tq6.id})
ta25= Answer.create({content:"With a spell",solution:false, question_id:tq7.id})
ta26= Answer.create({content:"With his mouth",solution:true, question_id:tq7.id})
ta27= Answer.create({content:"With a glove",solution:false, question_id:tq7.id})
ta28= Answer.create({content:"With his broom",solution:false, question_id:tq7.id})
ta29= Answer.create({content:"He's an good killer with spells",solution:false, question_id:tq8.id})
ta30= Answer.create({content:"He can control dementors",solution:false, question_id:tq8.id})
ta31= Answer.create({content:"He can control trolls",solution:false, question_id:tq8.id})
ta32= Answer.create({content:"He's a parselmouth",solution:true, question_id:tq8.id})
ta33= Answer.create({content:"Severus snape",solution:true, question_id:tq9.id})
ta34= Answer.create({content:Faker::Movies::HarryPotter.character,solution:false, question_id:tq9.id})
ta35= Answer.create({content:Faker::Movies::HarryPotter.character,solution:false, question_id:tq9.id})
ta36= Answer.create({content:Faker::Movies::HarryPotter.character,solution:false, question_id:tq9.id})
ta37= Answer.create({content:"Ginny Weasley",solution:true, question_id:tq10.id})
ta38= Answer.create({content:Faker::Movies::HarryPotter.character,solution:false, question_id:tq10.id})
ta39= Answer.create({content:Faker::Movies::HarryPotter.character,solution:false, question_id:tq10.id})
ta40= Answer.create({content:Faker::Movies::HarryPotter.character,solution:false, question_id:tq10.id})
ta41 = Answer.create({content:"Alomora",solution:false, question_id:tq11.id})
ta42 = Answer.create({content:"Lumos",solution:true, question_id:tq11.id})
ta43 = Answer.create({content:"Radioso",solution:false, question_id:tq11.id})
ta44 = Answer.create({content:"Quantus",solution:false, question_id:tq11.id})
ta45 = Answer.create({content:"Quietus",solution:false, question_id:tq12.id})
ta46 = Answer.create({content:"Bombarda",solution:false, question_id:tq12.id})
ta47 = Answer.create({content:"Sonorus",solution:true, question_id:tq12.id})
ta48 = Answer.create({content:"Riviudus",solution:false, question_id:tq12.id})
ta49 = Answer.create({content:"Protean",solution:true, question_id:tq13.id})
ta50 = Answer.create({content:"Confundo",solution:false, question_id:tq13.id})
ta51 = Answer.create({content:"Obliviate",solution:false, question_id:tq13.id})
ta52 = Answer.create({content:"Umnicundous",solution:false, question_id:tq13.id})
ta53 = Answer.create({content:"A spider",solution:false, question_id:tq14.id})
ta54 = Answer.create({content:"A troll",solution:false, question_id:tq14.id})
ta55 = Answer.create({content:"A dragon",solution:true, question_id:tq14.id})
ta56 = Answer.create({content:"A spotter",solution:false, question_id:tq14.id})
ta57 = Answer.create({content:"Incendio",solution:true, question_id:tq15.id})
ta58 = Answer.create({content:"Levicorpus",solution:false, question_id:tq15.id})
ta59 = Answer.create({content:"Locomotor",solution:false, question_id:tq15.id})
ta60 = Answer.create({content:"Nerius",solution:false, question_id:tq15.id})
